### ISSUE TITLE
Auto plays GIF on page load in Chrome on the demo

### ISSUE THREAD

**Issue by jasondavis** [krasimir/gifffer#6] opened 2015-11-25 03:41 UTC
The demo URL http://work.krasimirtsonev.com/git/gifffer/example/ plays all the GIF images on page load and then shows the play button.  SO on initial page load it is auto loading and playing the GIFs, this is a bug?

I just saw the Stackoverflow post you linked as inspiration.  In a newer answer on that post here http://stackoverflow.com/a/24707088/143030 it has a cross-browser solution.  Would someone be able to integrate this new code into this library?  Would be grateful!

**Comment by krasimir** [comment] 2015-11-25 06:30
@jasondavis the solution requires to have the full image loaded. Even the link that you posted we have 
```
img.addEventListener('load', freeze, true);
```
but I'll leave this issue open and will try to fix that.

**Comment by krasimir** [comment] 2016-01-20 05:11
The idea of gifffer is to provide control to start the animation and to have the gif stopped by default. If the image is not loaded (i.e. the gif) we can't create the preview and we go back to the old fashion way - manually create a preview (in photoshop for example) place it on the page and replace it with the actual gif when click is registered. Closing this issue because the expected behavior of the library is to have all the gifs loaded in order to process them.

cc https://github.com/krasimir/gifffer/issues/5

**Closed by krasimir** 2016-01-20 05:12 UTC
